### ISSUE TITLE
where is the API key registration form?

### ISSUE THREAD

**Issue by lsoares** [OneStopTransport/OneStopTransport#4]
I can't find it.

**Comment by rjvitorino** [comment]
Hi @lsoares, have you followed our tutorial? 

https://github.com/OneStopTransport/OneStopTransport/wiki/Autenticac%CC%A7a%CC%83o-por-chave

There, you can find info on how to create an API Key or OAuth tokens.
Cheers

**Comment by lsoares** [comment]
well. I followed it now. **It is not clear** from the website that I should have done it or that was the starting point.

I registered a key but I get 401 in the API Explorer calls.

**Comment by rjvitorino** [comment]
Sorry for that. We have a [Developer FAQ](https://github.com/OneStopTransport/OneStopTransport/wiki/Developer-faq) that tries to point out where to start. The main website has pointers in the landing page to the developers documentation, available here on GitHub, which is this [wiki](https://github.com/OneStopTransport/OneStopTransport/wiki).

Regarding the API Keys, please note that to work on the browser (API Explorer) it should be a `browser key` while on other applications (mobile apps, web servers, scripts, snippets, etc.), you'll need a `server key`. Documented here: https://github.com/OneStopTransport/OneStopTransport/wiki/Autenticac%CC%A7a%CC%83o-por-chave#tipos-de-chave

Thank you for your issues,
Good work!
Cheers

**Comment by lsoares** [comment]
Hi Ricardo,

can you give me an example where this works?
https://api.ost.pt/trips/plan/?optimize=QUICK&time=10%3A00am&arriveBy=true&fromPlace=38.7562355%2C-9.2389484&toPlace=38.7180856,-9.1361095&date=2016-04-08&mode=TRANSIT&key=?
??
I only get null as result.

BTW, is there an API for buses at location? What about real time next
arrivals at that location?

---

Luís Soares
luissoares.com

**Comment by rjvitorino** [comment]
Hello again, I would like to ask you to please use a different GitHub issue for different problems, in order to ease the work for other developers.

Regarding your example, if you change the mode to `TRANSIT,WALK` you'll be able to retrieve results from the service, most likely there's no public transportation or road near the points (I haven't checked).

I didn't understand the concept "buses at location", and regarding real-time arrivals, sadly our data providers haven't given us access to it. Please find below all the APIs and resources available at OST: https://github.com/OneStopTransport/OneStopTransport/wiki/Dados-e-Servi%C3%A7os

Best regards
